apiVersion: apps/v1
kind: Deployment
metadata:
  name: dividend-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dividend-tracker
  template:
    metadata:
      labels:
        app: dividend-tracker
    spec:
      containers:
        - name: backend
          image: dividend_tracker:V1
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/stock_dividend_tracker

            - name: SPRING_DATASOURCE_USERNAME
              value: postgres

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: db-password

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: api-key

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
