apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dividend-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: dividend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dividend-tracker-service
                port:
                  number: 8080